title: Hacker On-Boarding
baseURL: https://dev.dsmhack.org/
googleAnalytics: UA-84353642-2
params:
  favicon: images/dsmhack-avatar.png
  logo_url: https://dsmhack.org
  primary_logo: /images/dsmhack.png
  mobile_logo: /images/dsmhack-avatar.png
  social:
  - icon: github
    url: https://github.com/dsmHack/dev.dsmhack.org
  - icon: facebook-square
    url: https://facebook.com/dsmhack
  - icon: twitter
    url: https://twitter.com/dsmhack
  - icon: instagram
    url: https://instagram.com/dsm_hack
  - icon: linkedin
    url: https://linkedin.com/company/dsmhack
  palette: blue
  palettes:
    blue:
      sass:
        bg: '#253149'
        accent1: '#4167a6'
        accent2: '#3f8eb3'
        accent3: '#4ca07e'
    green:
      sass:
        bg: '#20313d'
        accent1: '#2e9692'
        accent2: '#3aa4ca'
        accent3: '#b84d50'
    purple:
      sass:
        bg: '#312450'
        accent1: '#5e42a6'
        accent2: '#5052b5'
        accent3: '#b74e91'
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
